version: '3.8'
services:
  sneakers:
    build: .
    image: sneakers
    container_name: sneakers
    volumes:
      - ${PATH_IMG}:/usr/projet-i3-sneaker/img/test/
      - ${PATH_OUT}:/usr/projet-i3-sneaker/out/
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge