# devs: 
#   to get data from this file, use: 
#       ConfigLoader.getVariable('loader', 'batchSize')    (for exemple)


runConfig:
    nbProcess: default      # -> 'default' calculates for the number of processors you have.
                            #       - some may be idling from time to time.
                            # -> 'auto' will auto adjusts the number of processes in accordance with the number of pending tasks
                            # -> any strictly positive number: sets the number of processes to this number.
    
    talkative:              # all these options are for console messages with print()
        processes: False    # to see the messages of the processes starting/ending
        ias:       False    # to see the messages of the processing happening in each Blackbox. 
        loader:    False    # to see the messages of the loader
        
output:
    data: ../out/data.json          # the output for image tags
    testData: ../out/testData.json  # the output file where we dump stuff that does not really matter, when we test stuff

loader:
    localImgSrc: ../img/test/
    batchSize: 4      # how many images should the loader load at once in the system
    reloadNumber: 1   # When we reach this number of loaded images or less, we try to load more.

background:
    b: (0.0,1.0,0.0)
    r: (0.0,0.0,1.0)
    g: (1.0,0.0,0.0)