# devs: 
#   to get data from this file, use: 
#       ConfigLoader.getVariable('loader', 'batchSize')    (for exemple)
#   The data is loaded whole in the ConfigLoader, and then reloaded on demand.


runConfig:

    stopsAtEnd: True  # When all the images in the database are dealt with, should we stop? 

    nbProcess: 4      # -> 'default' calculates for the number of processors you have.
                            #       - some may be idling from time to time.
                            # -> 'auto' will auto adjusts the number of processes in accordance with the number of pending tasks
                            # -> any strictly positive number: sets the number of processes to this number.
    
    talkative:              # all these options are for console messages with print()
        processes:      True    
        messages:       False    
        ias:            True    
        ias-detailed:   False    
        loader:         False    
    
    logs: 
        file:           ../out/logs.log
        removePrevious: False
        processes:      False  
        messages:       False   
        ias:            False   
        ias-detailed:   False  
        loader:         False

    gui:
        showImages: True       # Show each image when processed (stops the Blackbox from processing other images while the image is on display!!!)

    dynamicConfig: False        # Setting to True reloads the configuration from the file at each loop of the BlackBox and of the main.  
                                # This allows you to change the config while the application is running and see the effects in live.      
                                # /!\ Loading values from a file frequently has an impact on the running time of the app (not much, but still). 
                                # /!\ If you want to set it to True, you NEED TO SET IT BEFORE RUNNING THE APPLICATION.
output:
    data: ../out/data.json          # the output for image tags
    testData: ../out/testData.json  # the output file where we dump stuff that does not really matter, when we test stuff

input:
    # to train our IAs
    trainingImagesFolder: ../img/train/trainingTestImages   # the home folder for all images to train our ia
    shoeDetectAndExtractTrainData: ../in/trainData.json     # the data to train the IA that detects the presence of sneakers 
    shoeTypeTrainData: ../in/trainData.json                 # the data to train the IA that detects the type of sneaker
    nomore: ../img/nomore.png                               # the displayed image to inform there are no more images when labelling by hand

loader:
    takeFromLocalSource: True  
    localImgSrc: ../img/test/
    remoteImgSrc: /resources
    batchSize: 5      # how many images should the loader load at once in the system
    reloadNumber: 4   # When we reach this number of loaded images or less, we try to load more.

background:
    g: (0.0,1.0,0.0)
    r: (0.0,0.0,1.0)
    b: (1.0,0.0,0.0)

color_detection:
    attempts: 10    # Max iteration for kmeans function
    margin: 20      # Margin for pixel detection when calculating the ratio
    seuil: 0.25    
    
shoeDetection:
    modelFilePath: ../in/AI/DetectShoes/model.h5
    weightsFilePath: ../in/AI/DetectShoes/weights.h5