# devs: 
#   to get data from this file, use: 
#       ConfigLoader.getVariable('loader', 'batchSize')    (for exemple)
#   The data is loaded whole in the ConfigLoader, and then reloaded on demand.

runConfig:
    nbProcess: 8      # -> 'default' calculates for the number of processors you have.
                            #       - some may be idling from time to time.
                            # -> any strictly positive number: sets the number of processes to this number.
    
    talkative:              # all these options are for console messages with print()
        processes:      True    
        messages:       False    
        ias:            True    
        ias-detailed:   False  
        loader:         True   
        tensorflow:     4 
    
    logs: 
        file:           ../out/logs.log
        removePrevious: True
        processes:      False  
        messages:       True   
        ias:            False   
        ias-detailed:   False  
        loader:         False

    gui:
        showImages: False      # Show each image when processed (stops the Blackbox from processing other images while the image is on display!!!)

output:
    data: ../out/data.json          # the output for image tags
    testData: ../out/testData.json  # the output file where we dump stuff that does not really matter, when we test stuff
    tempData: ../out/temp
    keepTempFiles: False

input:
    # to train our IAs
    trainingImagesFolder: ../img/train/trainingTestImages   # the home folder for all images to train our ia
    shoeDetectAndExtractTrainData: ../in/trainData.json     # the data to train the IA that detects the presence of sneakers 
    shoeTypeTrainData: ../in/trainData.json                                 # the displayed image to inform there are no more images when labelling by hand

loader:
    takeFromLocalSource: True  
    localImgSrc: ../img/test/
    remoteImgSrc: /resources
    remoteCoIds : 
        host: ~
        user: ~
        pswd: ~
    batchSize: 15      # how many images should the loader load at once in the system
    reloadNumber: 10   # When we reach this number of loaded images or less, we try to load more.
    doneFile: ../in/done.txt

background:
    g: [0.0, 1.0, 0.0]
    r: [0.0, 0.0, 1.0]
    b: [1.0, 0.0, 0.0]

color_detection:
    attempts: 10    # Max iteration for kmeans function
    margin: 20      # Margin for pixel detection when calculating the ratio
    seuil: 0.25    
    
neuronNetworks:
    shoeDetectModelFilePath: ../in/AI/DetectShoes/model.h5
    shoeDetectWeightsFilePath: ../in/AI/DetectShoes/weights.h5
    typeDetectModelFilePath: ../in/AI/DetectType/model.h5
    typeDetectWeightsFilePath: ../in/AI/DetectType/weights.h5

