# devs: 
#   to get data from this file, use: 
#       ConfigLoader.getVariable('loader', 'batchSize')    (for exemple)


runConfig:
    nbProcess: default             # 'default' calculates for the number of procs you have.

output:
    data: ../out/data.json         # the output for image tags
    testData: ../out/testData.json # the output file where we dump stuff that does not really matter, when we test stuff

loader:
    localImgSrc: ../img/test/
    batchSize: 4      # how many images should the loader load at once in the system
    reloadNumber: 1   # When we reach this number of loaded images or less, we try to load more.
